import * as vscode from 'vscode';
import * as path from 'path';
import * as cp from 'child_process';
import { parse, ParseError } from 'jsonc-parser';
import { jsonnetDiff } from './diff';
import { registerDiffProvider, showDiff } from './diff_virtual_doc';
import { doMerge as doMergeImpl, doOverwrite as doOverwriteImpl, findFragments } from './merge';

export function activate(context: vscode.ExtensionContext) {
    const output = vscode.window.createOutputChannel('Layered Settings');
    registerDiffProvider(context);

    context.subscriptions.push(
        output,
        vscode.commands.registerCommand('layeredSettings.generateDiff', async () => {
            const scope = await pickScope(context);
            if (scope) await generateDiff(scope.dir, output);
        }),
        vscode.commands.registerCommand('layeredSettings.overwrite', async () => {
            const scope = await pickScope(context);
            if (scope) await doOverwrite(scope.dir, output);
        }),
    );

    setupWatchers(context, output);
}

interface Scope {
    label: string;
    dir: string;
}

// "Scopes" are settings file locations. The three possible scopes are
// workspace, user, and remote.
function getAvailableScopes(context: vscode.ExtensionContext): Scope[] {
    const scopes: Scope[] = [];
    const isUI = context.extension.extensionKind === vscode.ExtensionKind.UI;
    const isRemote = !!vscode.env.remoteName;

    if (isUI) {
        scopes.push({ label: 'User Settings', dir: resolveGlobalSettingsDir(context) });
    }

    if (!isUI) {
        if (isRemote) {
            const label = getRemoteLabel();
            scopes.push({ label: `Remote Settings (${label})`, dir: resolveGlobalSettingsDir(context) });
        }
        const folders = vscode.workspace.workspaceFolders ?? [];
        for (const folder of folders) {
            scopes.push({
                label: `Workspace Settings: ${folder.name}`,
                dir: path.join(folder.uri.fsPath, '.vscode'),
            });
        }
    }

    if (isUI && !isRemote) {
        const folders = vscode.workspace.workspaceFolders ?? [];
        for (const folder of folders) {
            scopes.push({
                label: `Workspace Settings: ${folder.name}`,
                dir: path.join(folder.uri.fsPath, '.vscode'),
            });
        }
    }

    return scopes;
}

// Prompt the user to choose a settings scope (workspace, user, remote). Returns
// immediately if only one scope exists.
async function pickScope(context: vscode.ExtensionContext): Promise<Scope | undefined> {
    const scopes = getAvailableScopes(context);

    if (scopes.length === 0) {
        vscode.window.showErrorMessage('Layered Settings: No settings scopes available.');
        return undefined;
    }
    if (scopes.length === 1) return scopes[0];

    const picked = await vscode.window.showQuickPick(
        scopes.map(s => ({ label: s.label, scope: s })),
        { placeHolder: 'Choose a settings scope' },
    );
    return picked?.scope;
}

function getRemoteLabel(): string {
    const type = vscode.env.remoteName ?? 'Remote';
    const authority = process.env.VSCODE_REMOTE_AUTHORITY ?? '';
    const plusIdx = authority.indexOf('+');
    const host = plusIdx >= 0 ? authority.slice(plusIdx + 1) : '';
    if (host) return `${type}: ${host}`;
    return type;
}

// Returns the global settings directory for this host: local user settings or remote Machine settings.
function resolveGlobalSettingsDir(context: vscode.ExtensionContext): string {
    if (vscode.env.remoteName) {
        return path.resolve(context.globalStorageUri.fsPath, '..', '..', '..', 'Machine');
    }
    return path.resolve(context.globalStorageUri.fsPath, '..', '..');
}


// Generate settings.~diff.jsonnet capturing the diff between the
// combined fragments and settings.json.
async function generateDiff(userDir: string, output: vscode.OutputChannel) {
    try {
        const allFragments = await findFragments(userDir, vscode);

        let base: Record<string, any> = {};
        if (allFragments.length) {
            base = await evalFragments(userDir, allFragments);
        }

        const settingsPath = path.join(userDir, 'settings.json');
        const target = await readJsonc(settingsPath) ?? {};

        const body = jsonnetDiff(base, target, 1);
        await showDiff('// Auto-generated by Layered Settings.\n{\n' + body + '}\n');

        output.appendLine('[diff] Generated diff');
    } catch (err: any) {
        const msg = err?.message ?? String(err);
        output.appendLine(`[error] ${msg}`);
        vscode.window.showErrorMessage(`Layered Settings: ${msg}`);
    }
}

async function evalFragments(userDir: string, files: string[]): Promise<Record<string, any>> {
    const expr = files
        .map(f => `(import '${f}')`)
        .join('\n+ ');

    const result = await execJsonnet(['-J', userDir, '-e', expr]);
    const parsed = JSON.parse(result);
    if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
        throw new Error('Jsonnet evaluation did not produce a JSON object');
    }
    return parsed;
}

function execJsonnet(args: string[]): Promise<string> {
    return new Promise((resolve, reject) => {
        cp.execFile('jsonnet', args, { maxBuffer: 10 * 1024 * 1024 }, (err, stdout, stderr) => {
            if (err) {
                reject(new Error(stderr.trim() || err.message));
            } else {
                resolve(stdout);
            }
        });
    });
}

async function readJsonc(filePath: string): Promise<Record<string, any> | undefined> {
    try {
        const data = await vscode.workspace.fs.readFile(vscode.Uri.file(filePath));
        const text = Buffer.from(data).toString('utf8');
        const errors: ParseError[] = [];
        const obj = parse(text, errors, {
            allowTrailingComma: true,
            disallowComments: false,
        });
        if (errors.length) {
            vscode.window.showWarningMessage(`Layered Settings: Parse errors in ${path.basename(filePath)}`);
        }
        return typeof obj === 'object' && obj !== null && !Array.isArray(obj) ? obj : undefined;
    } catch {
        return undefined;
    }
}


// Combine all settings.xxx.jsonnet files with + and write the result into
// settings.json, preserving any user edits above the old generated base.
// Skips silently if fragments are unchanged. Safe to call from watchers.
export async function doMerge(settingsDir: string, output: vscode.OutputChannel) {
    return doMergeImpl(settingsDir, output, vscode);
}

async function doOverwrite(settingsDir: string, output: vscode.OutputChannel) {
    return doOverwriteImpl(settingsDir, output, vscode);
}


function setupWatchers(context: vscode.ExtensionContext, output: vscode.OutputChannel) {
    const scopes = getAvailableScopes(context);

    for (const scope of scopes) {
        const pattern = new vscode.RelativePattern(vscode.Uri.file(scope.dir), 'settings.*.jsonnet');
        const watcher = vscode.workspace.createFileSystemWatcher(pattern);

        let timer: ReturnType<typeof setTimeout> | undefined;
        const debounced = () => {
            if (timer) clearTimeout(timer);
            timer = setTimeout(() => { doMerge(scope.dir, output); }, 500);
        };

        watcher.onDidChange(debounced);
        watcher.onDidCreate(debounced);
        watcher.onDidDelete(debounced);
        context.subscriptions.push(watcher);

        doMerge(scope.dir, output);
    }
}

export function deactivate() {}
